### ISSUE TITLE
Migrate issues from bitbucket

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozbuzz#1]
We need to migrate all open issues from bitbucket here:

https://bitbucket.org/mozillahispano/mozbuzz/issues?status=new&status=open

**Comment by peregrinogris** [comment]
Well, I did some research.

We have two things to look at:
- The [Github API](http://developer.github.com/)
- The [Bitbucket API](http://confluence.atlassian.com/display/BITBUCKET/Using+the+bitbucket+REST+APIs;jsessionid=FD55D3D5888352704B0809F495FE2D80)

We have a list of resources to do this, as follows:
- From the Github side:
  - Github official libraries http://developer.github.com/v3/libraries/
  - Python library for github https://github.com/ask/python-github2/
  - Javascript library https://github.com/fitzgen/github-api
- From the Bitbucket side:
  - No library-love from Bitbucket

I also found some examples that while they don't solve the problem, they might be useful for this task:
- Python Brokers in bitbucket http://confluence.atlassian.com/display/BITBUCKET/Writing+Brokers+for+bitbucket
- Python Github-Pivotal exporter https://gist.github.com/768875
- Tract-to-Github exporter (PHP) https://github.com/trustmaster/trac2github

From all that we should manage to get something working. The hardest part I think is from bitbucket, as there are not many examples using their API.

I would go with python as it seems to be a good compromise between our know-how and available libraries. Also try to make this as generic as possible, as it seems there is no resource on the internet to do what we want to do and it might be useful to others.

**Comment by nukeador** [comment]
@peregrinogris would you be able to it? We need it done before calling for developers.

**Comment by nidico** [comment]
As we're having the same task ahead: Have you actually written a generic solution? I see your bitbucket repo doesn't exist anymore...

**Comment by nukeador** [comment]
@nidico I think that, at the end, we migrated them manually. /cc @felipelerena @peregrinogris

**Comment by nidico** [comment]
For the protocol (and because this issue is the top google search hit for _github bitbucket migrate issues_):

I created a small migration script, which simplifies the task, using client libraries for both Bitbucket and GitHub
https://gist.github.com/3778347

Caution: It definitely needs some customization in order to work, and you need to know Python in order to use it.

**Comment by sebasmagri** [comment]
Hi guys.

I found that the bitbucket repo were already removed. Does it still make sense to keep this issue open? Were all issues migrated to Github?

Best Regards.

**Comment by nukeador** [comment]
Yep, they should.
