### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by rlr** [mozillahispano/mozbuzz#16]
I am not sure what license you usually use for m-h? If it helps, we usually use the 3 clause BSD license for webdev projects. Like:

https://github.com/mozilla/kitsune/blob/master/LICENSE

**Comment by nukeador** [comment]
We use GPL3 for every web project at Mozilla Hispano and cc-by-sa for content on the site. So yes, we should indicate that on the source.

**Comment by bbotella** [comment]
@sebasmagri So, this implies copying the license file inside the root folder, isn't it? Anything else? If so, I'll do it today.

**Comment by sebasmagri** [comment]
@bbotella Yes it is!. However there is a LICENSE file already in the django15 branch. Lets leave this for the django15 merge.

**Comment by bbotella** [comment]
So, should we close this ticket?

**Comment by sebasmagri** [comment]
This is already in the development branch.
