### ISSUE TITLE
Filters can't be disabled by clicking

### ISSUE THREAD

**Issue by fjaguero** [mozillahispano/mozbuzz#24]
If you set a property by clicking (country, for ex.) then you can't ignore that property by clicking on the same attribute again. The only way to reset the filters is reloading the page.

Will improve the usability the possibility to enable/disable the filter's attributes by clicking twice?

**Comment by dvdbng** [comment]
You should be able to deselect it by shift-clicking it, but shift-clicking doesn't work on my system and just opens the link in a new window, does this happens to somebody else?

**Comment by fjaguero** [comment]
I saw the "shift+click" message on the app but it behaves like you said.
