### ISSUE TITLE
https://mozilla-hispano.org/mozbuzz/ Does not update

### ISSUE THREAD

**Issue by dvdbng** [mozillahispano/mozbuzz#28]
https://mozilla-hispano.org/mozbuzz/ Stopped updating after revision f1e16e792a34ac2efe1abe3538b314a8fe4eb7ca

**Comment by dvdbng** [comment]
Parece que ya funciona, gracias

**Comment by nukeador** [comment]
El cron está programado cada 30 minutos, avisad de nuevo si vuelve a dejar de actualizar, ya que no hemos tocado nada para que vuelva.
