### ISSUE TITLE
Admin interface css not found

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozbuzz#29]
Go to https://www.mozilla-hispano.org/mozbuzz/admin/ 

Css stiles not found:

https://www.mozilla-hispano.org/mozbuzz/admin-media/css/base.css

On nginx virtualhost:
## 
# Mozbuzz
## 

```
    location ^~ /mozbuzz/admin-media {
            alias /usr/share/pyshared/django/contrib/admin/media;
    }
```

**Comment by willyaranda** [comment]
Done, was here: `/usr/local/lib/python2.6/dist-packages/django/contrib/admin/media`
