### ISSUE TITLE
Create install documentation

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozbuzz#3]
We need documentation about how to install and deploy this app.

**Comment by ccarruitero** [comment]
It's not the same of README?

**Comment by willyaranda** [comment]
No, README is for "What is this?" "How to collaborate?". INSTALL documentation should be another document

**Comment by bbotella** [comment]
Noted down for the next doc file. By the way, would it be a good idea to open a new issue and attach it to a further project version to remember to make it less OS dependent?

**Comment by sebasmagri** [comment]
@bbotella could we merge this doc with the admin documentation at https://github.com/mozillahispano/mozbuzz/blob/development/docs/admin/index.rst?

Regards

**Comment by sebasmagri** [comment]
I'm closing this as I consider docs at docs/admin/index.rst are sufficient.

**Comment by bbotella** [comment]
Sure. I’ll do it asap and I will make the pull request. I hope to have it for tomorrow.
