### ISSUE TITLE
import docs in readthedocs.org

### ISSUE THREAD

**Issue by ccarruitero** [mozillahispano/mozbuzz#31]

**Comment by marti1125** [comment]
Is useful for you =?
https://mozzbuzz.readthedocs.org/en/latest/

**Comment by nukeador** [comment]
@marti1125 can you transfer the ownership of that to tecnico at mozilla-hispano.org please?

**Comment by marti1125** [comment]
I didn't see an option to transfer via email only via username.
If you want to become a Maintainers, You will create an account in readthedocs.org, and give me your username for add it.

**Comment by marti1125** [comment]
ok, I added https://readthedocs.org/profiles/mozillahispano/

**Comment by nukeador** [comment]
Closing, please link this page from the README.
