### ISSUE TITLE
Create add-on or Social API widget to "Share on mozbuzz"

### ISSUE THREAD

**Issue by nukeador** [mozillahispano/mozbuzz#33]
It would be great to have a super simple (restartless) add-on for Firefox or a Social API widget to share an article you are reading on mozbuzz directly.

We would just need a context menu and/or icon on awesome bar, much like Fb like.

**Comment by ccarruitero** [comment]
It's not be better do this from inside mozbuzz?

**Comment by nukeador** [comment]
Re-thinking about it, maybe we could integrate Social API inside mozbuzz and expose a "Share on mozbuzz" feature on the awesome bar.

**Comment by nukeador** [comment]
Forget about the Social API thing, I've been told it won't be open to other providers till nex 2 or 3 stable versions. Let's do a quick add-on for now.

**Comment by ccarruitero** [comment]
Forget my previous comment. I don't read good in that moment.

Social API, sounds interesting :D. Let me see if I can do something in this week

**Comment by nukeador** [comment]
@ccarruitero Read my previous comment, currently is not possible to implement other providers, we would have to wait 2-3 stable versions.

**Comment by ccarruitero** [comment]
ok

**Comment by ccarruitero** [comment]
Hi,

Sorry, I was busy this week. MozBuzz have an api? @nukeador @felipelerena @YouWoTMA

**Comment by nukeador** [comment]
@ccarruitero AS far as I know, no. Then maybe the first step would be create one :P

**Comment by dvdbng** [comment]
I don't think it's necessary an API for the moment, this simple bookmarklet can do what you want without need of further changes to mozbuzz (create a new bookmark and put this as the address)

```
javascript:location.href="https://www.mozilla-hispano.org/mozbuzz/mention/create?url="+encodeURIComponent(location.href);
```

**Comment by nukeador** [comment]
@YouWoTMA Awesomic! :D

**Comment by ccarruitero** [comment]
great!, I will do addon tonight or tomorrow :)

**Comment by nukeador** [comment]
@ccarruitero A simple addon to add an icon inside location bar (similar to the one FB Social API adds) would work.

**Comment by ccarruitero** [comment]
sorry for delay, here is a code
https://github.com/ccarruitero/mozbuzz-addon

and a xpi
https://dl.dropbox.com/u/1711055/mozbuzz-addon.xpi

currently I use firefox image, but this should be changed when have another image

**Comment by nukeador** [comment]
@ccarruitero Let's move this addon to MH github. BTW it's not working for me.

https://github.com/mozillahispano/mozbuzz-share

I close this issue and let's use the project issues for tracking problems/improvements
