### ISSUE TITLE
Fatal error accessing MozBuzz

### ISSUE THREAD

**Issue by bernimel** [mozillahispano/mozbuzz#36]
Hi, 

I've tried to access to MozBuzz today and the website is not available. It's sending me to https://www.mozilla-hispano.org/mozbuzz/accounts/login/?next=/mozbuzz/. 

Could you please help? @YouWoTMA @sveggiani @fjaguero

**Comment by sebasmagri** [comment]
I was able to reproduce this error by using django-browserid-0.7, so probably the cause is an outdated version of this dep.

**Comment by nukeador** [comment]
django-browserid upgraded to 0.8
