### ISSUE TITLE
Port to Django 1.5.x

### ISSUE THREAD

**Issue by sebasmagri** [mozillahispano/mozbuzz#42]

**Comment by nukeador** [comment]
I thought it was already ported, in fact the server uses 1.5.1 right now.

**Comment by sebasmagri** [comment]
Right. This issue is more about getting rid of obsolete parts and fixing all deprecation warnings, as well as using Django 1.5.x projects layout.

**Comment by bbotella** [comment]
Today has been released Django 1.6. Should we port it to the newest version?

**Comment by sebasmagri** [comment]
It makes sense for me.

**Comment by nukeador** [comment]
I.T has a pending task to deploy django instances at mozilla hispano using a virtualenv, which will help individual projects to use the django version they need ;)

**Comment by sebasmagri** [comment]
That's very good.

I believe it's good to have this running on the latest Django version. However we might be always upgrading the project and it would affect the progress on other issues. So let's choose a base version to work on the pending issues and after that we can upgrade to the latest Django.

What do you think?

**Comment by bbotella** [comment]
Sure, let’s make some kind of roadmap to get things done.

**Comment by sebasmagri** [comment]
Such a roadmap is at ROADMAP.rst. Any suggestion is welcome.

**Comment by bbotella** [comment]
Seen. Sorry again I missed it. I'll stick to it.

**Comment by sebasmagri** [comment]
I'm closing this as per the implemented changes in the development branch.
