### ISSUE TITLE
Value error in 0008_auto__add_field_rssfeed_product migration

### ISSUE THREAD

**Issue by ccarruitero** [mozillahispano/mozbuzz#49]
When try to run migrations I had a value error.
Log says need add default value, but I don't found a variable with null=False in models.
some idea?

This is the log [0]

[0] http://pastebin.com/8cDWSLkX

**Comment by dvdbng** [comment]
Hay que revertir este archivo a antes de este commit https://github.com/mozillahispano/mozbuzz/commit/dd95aa542fd975c79ca376ce16c4db9197376538#diff-faf8d02c3e12d71c6f79e90912ccbb8dL10
