### ISSUE TITLE
problem with login without persona

### ISSUE THREAD

**Issue by ccarruitero** [mozillahispano/mozbuzz#52]
After login with form I was logged out and redirect to login path.

I think maybe is a conflict with persona.

**Comment by sebasmagri** [comment]
The definite solution to Persona issues is going to be released in django-browserid 0.10. I will check this out anyway to see if we can workaround this or if we can backport some patches from upstream.

Best Regards,

**Comment by ccarruitero** [comment]
I think we need define loggedInUser[0] when logged in with form.

[0] https://github.com/mozilla/django-browserid/blob/master/django_browserid/static/browserid/browserid.js#L92

**Comment by sebasmagri** [comment]
I'm sorry, I misread the initial description and forgot the non-persona login issues.

Some time ago it was discussed in issue #38 to drop non persona login form and enforce persona usage. We should make a decision to see if we implement and test this as a workaround or if we finally drop non-persona login form.

**Comment by sebasmagri** [comment]
This is now fixed in the development branch. Thus, I am closing this. Please reopen if you think it should be open.
