### ISSUE TITLE
MozBuzz crash (CRITICAL)

### ISSUE THREAD

**Issue by bernimel** [mozillahispano/mozbuzz#56]
Hi, 

It's impossible to access to MozBuzz. I get the "ImproperlyConfigured at /mozbuzz/" error message. See attached URL for more information. 
http://oi44.tinypic.com/24xq3o3.jpg

cc @sebasmagri

**Comment by sebasmagri** [comment]
@nukeador are we deploying master automatically?

I realized I made a mistake and pushed a wrong merge to master. I already reverted this and backed up recent commits in django15. My bad.

Regards,

**Comment by nukeador** [comment]
@sebasmagri Yes, we've always been. Do you want to change that?

**Comment by sebasmagri** [comment]
No, It's better to change the workflow we're using and start doing everything in the development branch. I just want to make sure that the latest revert fixes the issue. Because of the dropped commits, probably a fresh clone of master will be needed.

**Comment by bbotella** [comment]
I am still having the issue.

**Comment by nukeador** [comment]
Emmm, that could be tricky since we have some local files not tracked. There should be a way to fix local copy, and could be a problem to contributors local copies too.

**Comment by nukeador** [comment]
Pull from master on the server does nothing, everything is "updated". Try to fix the repository to avoid this, as I said, it's problematic for all local copies.

**Comment by sebasmagri** [comment]
Ok, so we will have to revert the deployed master. This would work:

```
git reset ea84d4a91adb1f057d3e933462e0a5588e1d8da7 --hard
```

That's the same cset as github's master right now.

**Comment by nukeador** [comment]
Done, but:

```
# /root/bin/mozbuzz-update 
Already up-to-date.
/usr/local/lib/python2.6/dist-packages/django/core/management/__init__.py:465: DeprecationWarning: The 'execute_manager' function is deprecated, you likely need to update your 'manage.py'; please see the Django 1.4 release notes (https://docs.djangoproject.com/en/dev/releases/1.4/).
  DeprecationWarning)
/usr/local/lib/python2.6/dist-packages/django/core/management/__init__.py:409: DeprecationWarning: The 'setup_environ' function is deprecated, you likely need to update your 'manage.py'; please see the Django 1.4 release notes (https://docs.djangoproject.com/en/dev/releases/1.4/).
  DeprecationWarning)
? You have no migrations for the 'buzz' app. You might want some.
```

**Comment by nukeador** [comment]
It seems we lost a commit.

With 92c87baefb7183329d77690a011df089834c83c8, site is up and running.

**Comment by sebasmagri** [comment]
Ok. Thanks  @nukeador.

I'm sorry, won't happen again.

Regards,
