### ISSUE TITLE
Unable to access with Persona

### ISSUE THREAD

**Issue by bernimel** [mozillahispano/mozbuzz#63]
Hi, 

I'm trying to access to the tool and the system doesn't allow me. See error message on http://awesomescreenshot.com/0cb26w7i4c

**Comment by nukeador** [comment]
It seems request is not using www in the url.

**Comment by sebasmagri** [comment]
@bernimel Hi, you will need to use https://www.mozilla-hispano.org/mozbuzz/ until we upgrade to the next django-browserid release.

Regards,

**Comment by bernimel** [comment]
I'm in. Thank you!
